# This file is managed by `git_helper`. Don't edit it directly

language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:

  - pip install pip  --upgrade
  - pip install tox tox-travis
  - pip install coveralls

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda
  - deploy_releases

jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/mathematical
        provider: pypi
        user: "DomDF"
        password:
          secure: EUc8A5PPUpJh0bcrYcBWCToUnkpakzTcU03vtheJG95nT2Jtn/Hq8UcC7vDLSqUWFQEHYCL3i0g1DLSdQYtPMAbKfWXI5ieuVgMM2OEeNF5O2flPi2LberAtoLxNuisVsJkhh0uURXi5EDCX3PcTqtP0N3chawXGWD2MJAfx3VAHyHobb4xX8VM6eQJvKBS4OXf38OcZQwJdGwDtrmgPrbJoHQHBPYyPuvI9dwxw53JSWzTYPo5/HfXAEotiXM2PJDgl9WZygd4c9hP+tGckJtIBucF9k1eCAE3vC2kqBaiJepp2LG7GzAbzek+ky2eFj3y8RViOLm0SewsfVtU9/Ik39DQP27y5lx2G80u0D819Qpq19AIU/ZLJdlFyN+7RtXDNt+cz+s564PH6wnoYNLwYktktJILOQu3RIxi/DUash/cc1Gr12v1B0TSUotCpYrt0oPkC1y6AlPZNgOKf/IY0HgeJFxsYZYQ9xMmv6voXTQkSflKq+8gPNzFwJI4asC5cEElh0rn2IY1LaZaOzF790DF1sgm6MbqXECt2JLewK5ky59Cw6ksyb9DPEZso8IRKo3yDdAfZliM5mY/6fmLJSP4PItr3IjERjVivflyzLDz5cbtQsjP5+ph2+RrZFSc47oNgXij3VJpoXIzJF96tB+qRifuotGX+h707T88=
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        on:
          repo: domdfcoding/mathematical
        provider: script
        script: .ci/travis_deploy_conda.sh || travis_terminate 1;

    - stage: deploy_releases
      python: "3.6"
      install:
        - pip install PyGithub requests
      script: skip
      deploy:
        on:
          repo: domdfcoding/mathematical
        provider: script
        script: python .ci/copy_pypi_2_github.py || travis_terminate 1;
